import jsPDF from "jspdf";
import { CareEntry } from "./storage";

export function generatePDF(entries: CareEntry[]) {
  const doc = new jsPDF();
  
  doc.setFontSize(22);
  doc.setTextColor(40, 40, 40);
  doc.text("CareOctopus Health Report", 20, 20);
  
  doc.setFontSize(12);
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 30);
  
  doc.setLineWidth(0.5);
  doc.line(20, 35, 190, 35);

  let yPos = 50;

  entries.forEach((entry) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(`${entry.title} (${entry.type})`, 20, yPos);
    yPos += 7;

    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    
    const splitText = doc.splitTextToSize(entry.details, 170); 
    doc.text(splitText, 20, yPos);
    
    const textHeight = splitText.length * 5; 
    yPos += textHeight + 5;

    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(new Date(entry.timestamp).toLocaleString(), 20, yPos);

    yPos += 15;
  });

  doc.text("Generated by CareOctopus AI", 20, 290);

  doc.save("Patient_Report.pdf");
}